using System.Collections.Generic;
using UnityEngine;
using UnityEngine.AI;


public class PathwayNavMesh 
{
	private Pathway _pathway;
	
	public PathwayNavMesh(Pathway pathway)
	{
		_pathway = pathway;
		_pathway.Path = new List<Vector3>();
		_pathway.Hits = new List<Pathway.HitPoint>();
	}

	public bool PollsNavMesh()
	{
		NavMeshHit hit;
		bool hasHit;
		bool result = true;

		_pathway.Hits.Clear();

		for (int i = 0; i < _pathway.Waypoints.Count; i++)
		{
			hasHit = NavMesh.SamplePosition(_pathway.Waypoints[i], out hit, _pathway.MeshSize * 2, NavMesh.AllAreas);
			_pathway.Hits.Add(new Pathway.HitPoint(hasHit, hit.position));
			result &= hasHit;
		}

		return result;
	}

	private void CopyPathCorners(int startIndex, int endIndex, NavMeshPath navMeshPath, ref bool canGeneratePath) {

		canGeneratePath &= NavMesh.CalculatePath(_pathway.Waypoints[startIndex], _pathway.Waypoints[endIndex], NavMesh.AllAreas, navMeshPath);

		if (canGeneratePath)
		{
			for (int j = 0; j < navMeshPath.corners.Length; j++)
			{
				_pathway.Path.Add(navMeshPath.corners[j]);
			}
		}
		else
		{
			Debug.LogError("the path between " + startIndex + " and " + endIndex + " can't be generated by NavMeshPAth");
		}
	}

	public bool GenerateNavMeshPath()
	{
		bool canGeneatePath=true;
		int i = 1;
		NavMeshPath navMeshPath = new NavMeshPath();
		
		while ( i < _pathway.Waypoints.Count)
		{
			CopyPathCorners(i - 1, i, navMeshPath, ref canGeneatePath);
			i++;
		}

		CopyPathCorners(_pathway.Waypoints.Count-1, 0, navMeshPath, ref canGeneatePath);

		if (!canGeneatePath)
		{
			_pathway.Path.Clear();
		}

		return canGeneatePath;
	}

}
